// Generated by CoffeeScript 2.6.1
(function() {
  var countDirectons, depth, el, fs, horizontal, i, input, inputArray, inputFile, len, readFile;

  fs = require('fs');

  inputFile = 'input.txt';

  input = '';

  inputArray = [];

  depth = 0;

  horizontal = 0;

  readFile = function() {
    input = fs.readFileSync(inputFile, 'utf8');
    return inputArray = input.split('\r\n');
  };

  countDirectons = function(el) {
    var direction, value;
    [direction, value] = el.split(' ');
    switch (direction) {
      case "up":
        return depth -= Number(value);
      case "down":
        return depth += Number(value);
      case "forward":
        return horizontal += Number(value);
    }
  };

  readFile();

  for (i = 0, len = inputArray.length; i < len; i++) {
    el = inputArray[i];
    countDirectons(el);
  }

  console.log(depth * horizontal);

}).call(this);
