// Generated by CoffeeScript 2.6.1
(function() {
  var BingoBoard, bingoBoards, bingoNumbers, board, el, fs, i, input, j, k, len, len1, line, newLine, ref, tab;

  fs = require('fs');

  input = fs.readFileSync('input.txt', 'utf8').split('\n');

  bingoNumbers = input.shift().split(',');

  bingoBoards = [];

  tab = [];

  i = 0;

  for (j = 0, len = input.length; j < len; j++) {
    line = input[j];
    if (line !== '\r') {
      ((function() {
        var k, len1, ref;
        newLine = [];
        ref = line.split(' ');
        for (k = 0, len1 = ref.length; k < len1; k++) {
          el = ref[k];
          newLine.push(el.replace('\r', ''));
        }
        tab.push(newLine);
        i++;
        if (i === 5) {
          i = 0;
          bingoBoards.push(tab);
          return tab = [];
        }
      })());
    }
  }

  BingoBoard = class BingoBoard {
    constructor(table) {
      var col, k, len1, row;
      console.log('--------------');
      col = 0;
      row = 0;
      for (k = 0, len1 = table.length; k < len1; k++) {
        line = table[k];
        if (line !== '') {
          (board[line] = {
            value: line,
            col: col,
            row: row,
            picked: false
          }, console.log(board[line]));
        }
      }
    }

  };

  ref = bingoBoards[0];
  for (k = 0, len1 = ref.length; k < len1; k++) {
    board = ref[k];
    new BingoBoard(board);
  }

}).call(this);
