// Generated by CoffeeScript 2.6.1
(function() {
  var aim, changeDepthAndHorizontal, countDirectons, depth, el, fs, horizontal, i, input, inputArray, inputFile, len, readFile;

  fs = require('fs');

  inputFile = 'input.txt';

  input = '';

  inputArray = [];

  aim = 0;

  depth = 0;

  horizontal = 0;

  readFile = function() {
    input = fs.readFileSync(inputFile, 'utf8');
    return inputArray = input.split('\r\n');
  };

  changeDepthAndHorizontal = function(value) {
    horizontal += Number(value);
    return depth += Number(value * Number(aim));
  };

  countDirectons = function(el) {
    var direction, value;
    [direction, value] = el.split(' ');
    value = Number(value);
    switch (direction) {
      case "up":
        return aim -= value;
      case "down":
        return aim += value;
      case "forward":
        return changeDepthAndHorizontal(value);
    }
  };

  readFile();

  for (i = 0, len = inputArray.length; i < len; i++) {
    el = inputArray[i];
    countDirectons(el);
  }

  console.log(`Aim: ${aim} Depth: ${depth} Horizontal: ${horizontal}`);

  console.log(`Depth * Horizontal = ${depth * horizontal}`);

}).call(this);
