// Generated by CoffeeScript 2.6.1
(function() {
  var arrayA, arrayB, arrayC, fs, input, inputArray, readFile, removeTabs, transformToArray;

  fs = require('fs');

  input = 'input.txt';

  inputArray = [];

  arrayA = [];

  arrayB = [];

  arrayC = [];

  readFile = function() {
    return input = fs.readFileSync(input, 'utf8');
  };

  transformToArray = function() {
    var elem, i, len, results;
    inputArray = input.split('\n');
    results = [];
    for (i = 0, len = inputArray.length; i < len; i++) {
      elem = inputArray[i];
      results.push(inputArray = removeTabs);
    }
    return results;
  };

  removeTabs = function(str) {
    return str.replace('\r', '');
  };

  readFile();

  transformToArray();

  console.log(inputArray);

}).call(this);
