// Generated by CoffeeScript 2.6.1
(function() {
  var addElements, countResult, finalArray, finalResult, fs, input, inputArray, readFile, removeTab, transformToArray;

  fs = require('fs');

  input = 'input.txt';

  finalResult = 0;

  inputArray = [];

  finalArray = [];

  readFile = function() {
    return input = fs.readFileSync(input, 'utf8');
  };

  removeTab = function(str) {
    return str.replace('\r', '');
  };

  transformToArray = function() {
    var el, j, len, results;
    inputArray = input.split('\n');
    results = [];
    for (j = 0, len = inputArray.length; j < len; j++) {
      el = inputArray[j];
      results.push(finalArray.push(removeTab(el)));
    }
    return results;
  };

  addElements = function(elems) {
    var el, j, len, output;
    output = 0;
    for (j = 0, len = elems.length; j < len; j++) {
      el = elems[j];
      output += Number(el);
    }
    return output;
  };

  countResult = function() {
    var arrayA, arrayB, i, j, ref, results;
    results = [];
    for (i = j = 0, ref = inputArray.length; (0 <= ref ? j <= ref : j >= ref); i = 0 <= ref ? ++j : --j) {
      arrayA = finalArray.slice(i, +(i + 2) + 1 || 9e9);
      arrayB = finalArray.slice(i + 1, +(i + 3) + 1 || 9e9);
      console.log('-------------------');
      console.log(addElements(arrayA));
      console.log(addElements(arrayB));
      if ((addElements(arrayA)) < (addElements(arrayB))) {
        console.log('Increased');
        results.push(finalResult += 1);
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  readFile();

  transformToArray();

  countResult();

  console.log(finalResult);

}).call(this);
