// Generated by CoffeeScript 2.6.1
(function() {
  var epsilon, fs, gamma, i, input, j, oneTimes, record, ref, zeroTimes;

  fs = require('fs');

  input = fs.readFileSync('input.txt', 'utf8').split('\r\n');

  gamma = 0;

  epsilon = 0;

  for (i = j = 0, ref = input[0].length - 1; (0 <= ref ? j <= ref : j >= ref); i = 0 <= ref ? ++j : --j) {
    ((function() {
      var k, len;
      oneTimes = 0;
      zeroTimes = 0;
      for (k = 0, len = input.length; k < len; k++) {
        record = input[k];
        (record[i] === '1' ? oneTimes++ : record[i] === '0' ? zeroTimes++ : void 0);
      }
      if (oneTimes > zeroTimes) {
        gamma += 1 * 2 ** (input[0].length - 1 - i);
        return epsilon += 0 * 2 ** (input[0].length - 1 - i);
      } else {
        gamma += 0 * 2 ** (input[0].length - 1 - i);
        return epsilon += 1 * 2 ** (input[0].length - 1 - i);
      }
    })());
  }

  console.log(gamma * epsilon);

}).call(this);
